targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false