name: medusa_js_dart

description: A Dart client for interacting with the MedusaJS API.
version: 0.0.6
homepage: https://github.com/agostinofiscale/medusa-js-dart

environment:
  sdk: '^3.3.0'

dependencies:
  dio: ^5.4.1
  dio_smart_retry: ^5.0.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lint: ^2.0.0
  retrofit_generator: ^8.1.0
  test: ^1.25.2