enum ErrorType {
  queryRunnerAlreadyReleasedError,
  transactionAlreadyStartedError,
  transactionNotStartedError,
  conflict,
  unauthorized,
  paymentAuthorizationError,
  duplicateError,
  notAllowed,
  invalidData,
  notFound,
  databaseError,
  unexpectedState,
  invalidArgument,
  unknownError,
}
